name: Auto-merge PRs

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'CONTRIBUTORS.md' # Só roda se apenas este arquivo foi modificado

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Check if only CONTRIBUTORS.md was modified
        id: check-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if [[ "$CHANGED_FILES" != "CONTRIBUTORS.md" ]]; then
            echo "Error: Only CONTRIBUTORS.md can be modified!"
            echo "files_changed=false" >> $GITHUB_ENV
            exit 1
          fi
          echo "files_changed=true" >> $GITHUB_ENV

      - name: Check if only one line was added
        id: check-lines
        run: |
          ADDITIONS=$(git diff --unified=0 HEAD^ HEAD | grep '^+' | grep -v '+++' | wc -l)
          DELETIONS=$(git diff --unified=0 HEAD^ HEAD | grep '^- ' | wc -l)
          NET_CHANGE=$((ADDITIONS - DELETIONS))

          if [[ "$NET_CHANGE" -ne 1 ]]; then
            echo "Error: Only one net line change allowed!"
            echo "valid_lines=false" >> $GITHUB_ENV
            exit 1
          fi
          echo "valid_lines=true" >> $GITHUB_ENV

      - name: Merge PR
        id: merge
        if: env.files_changed == 'true' && env.valid_lines == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: "squash"
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "✅ Your contribution has been merged. Thank you! 🎉"
              });

            } catch (error) {
              console.error("Merge failed:", error);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "❌ Merge failed due to an unexpected error. Please check if your PR follows the contribution guidelines and try again."
              });

              throw error;
            }

      - name: Comment if PR fails validation
        if: env.files_changed == 'false' || env.valid_lines == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let message = "❌ Your PR did not meet the required conditions:\n";
            if (process.env.files_changed === 'false') {
              message += "- Only CONTRIBUTORS.md should be modified.\n";
            }
            if (process.env.valid_lines === 'false') {
              message += "- Only one line should be added.\n";
            }
            message += "\nPlease update your PR accordingly and try again. 🚀";

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
